<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>y</string>
		<string>yy</string>
		<string>ypp</string>
		<string>yxx</string>
		<string>y++</string>
		<string>bison</string>
		<string>BISON</string>
	</array>
	
	<key>name</key>
	<string>Yacc</string>
	
	<key>scopeName</key>
	<string>source.yacc</string>
	
	<key>injections</key>
	<dict>
		<!-- Inject injected.c++ into embedded.c++.yacc-->
		<!-- IMPORTANT: The names used for injections are EXTREMELY picky -->
		<key>cpp.yacc</key> 
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#injected.c++</string>
				</dict>
			</array>
		</dict>
	</dict>
	
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#decls.c++</string>
		</dict>
	</array>
	
	<key>repository</key>
	<dict>
		<key>decls.c++</key>
		<dict>
			<key>begin</key>
			<string>^%{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
				    <key>name</key>
				    <string>punctuation.separator.tag.section.yacc</string>
				</dict>
			</dict>
			
			<key>end</key>
			<string>^%}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
				    <key>name</key>
				    <string>punctuation.separator.tag.section.yacc</string>
				</dict>
			</dict>
			
			<key>name</key>
			<string>cpp.yacc</string>
		</dict>
		
		<!-- This is injected into embedded.c++.yacc in the injections dict -->
		<!-- DO NOT USE DIRECTLY -->
		<key>injected.c++</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c++</string>
				</dict>
			</array>
		</dict>
	</dict>
</dict>
</plist>
